brio_wu:
  rho_l: 1.0
  pres_l: 1.0
  u_l: 0.0
  v_l: 0.0
  w_l: 0.0
  rho_r: 0.125
  pres_r: 0.1
  u_r: 0.0
  v_r: 0.0
  w_r: 0.0
  x_discont: 6.0
  B_x_l: 0.75
  B_y_l: 1.0
  B_z_l: 0.0
  B_x_r: 0.75
  B_y_r: -1.0
  B_z_r: 0.0

  fluid: "glmmhd"

  tlim: 0.4
  dt: 0.025

sedov_noB:
  rho_a: 0.125
  u_a: 0.0
  v_a: 0.0
  w_a: 0.0
  p_a: 0.1
  rho_s: 1.0
  u_s: 0.0
  v_s: 0.0
  w_s: 0.0
  p_s: 1.0
  Rs: 0.2
  B_x: 0.0
  B_y: 0.0
  B_z: 0.0

  fluid: "euler"

  tlim: 2.0
  dt: 0.1

sedov_Bx:
  rho_a: 0.125
  u_a: 0.0
  v_a: 0.0
  w_a: 0.0
  p_a: 0.1
  rho_s: 1.0
  u_s: 0.0
  v_s: 0.0
  w_s: 0.0
  p_s: 1.0
  Rs: 0.2
  B_x: 0.1
  B_y: 0.0
  B_z: 0.0

  fluid: "glmmhd"

  tlim: 2.0
  dt: 0.1

sedov_By:
  rho_a: 0.125
  u_a: 0.0
  v_a: 0.0
  w_a: 0.0
  p_a: 0.1
  rho_s: 1.0
  u_s: 0.0
  v_s: 0.0
  w_s: 0.0
  p_s: 1.0
  Rs: 0.2
  B_x: 0.0
  B_y: 0.1
  B_z: 0.0

  fluid: "glmmhd"

  tlim: 2.0
  dt: 0.1

kh_noB:
  iprob: 4
  amp: 0.01
  vflow: 1.0
  vboost: 0.0
  dhro_rho0: 1.0
  drat: 2.0

  fluid: "euler"

  tlim: 2.0
  dt: 0.1

# NEED TO ADD KH WITH B

current_sheet:
  beta: 0.1
  A: 0.1

  fluid: "glmmhd"

  tlim: 1.0
  dt: 0.05

# NEED TO ADD TURBULENCE WHEN ITS READY

orszag_tang:
  fluid: "glmmhd"

  tlim: 1.0
  dt: 0.05